### ISSUE TITLE
velvet output

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/velvet#3]
I just noticed that velvet biobox produces the contigs in the bbx directory.
The initial idea of the output bbx directory was that it just contains the output biobox.yaml and later the log and nothing else.
However if this is confusing we should think about updating the rfc that there is no need to create the bbx directory.

**Comment by michaelbarton** [comment]
> I just noticed that velvet biobox produces the contigs in the bbx
> directory. The initial idea of the output bbx directory was that it just
> contains the output biobox.yaml and later the log and nothing else.
> However if this is confusing we should think about updating the rfc that
> there is no need to create the bbx directory.

This is reasonable I think. I think if the contigs and biobox.yaml are in
the same directory, then this directory could be used as the input to
another biobox. For example I would like to the preprocessor bioboxes to be
able to provide input to the assembler biobox.

For log files we could specify an additional, optional directory, where
these be stored placed. This could be a location for all metadata. A second
option could be to stream the logs to STDOUT/STDERR and then these could be
piped from the running container to the desired location.

Depending on what we decide on, we should update the SRA validator spec.

**Comment by pbelmann** [comment]
> This is reasonable I think. I think if the contigs and biobox.yaml are in
> the same directory, then this directory could be used as the input to
> another biobox. For example I would like to the preprocessor bioboxes to be
> able to provide input to the assembler biobox.

Ok, then I will update ray, soap and minia, so that their output is equal to velvet and state this in the rfc if this is not clear.

> For log files we could specify an additional, optional directory, where
> these be stored placed. This could be a location for all metadata. A second
> option could be to stream the logs to STDOUT/STDERR and then these could be
> piped from the running container to the desired location.

Yes, we should start thinking about log files. If we have different kinds of metadata we should use a directory with files instead of stdout/sterr. But it doesn't matter that much. Maybe create a short-term issue and wait two or three days if someone has an opinion to this?   

> Depending on what we decide on, we should update the SRA validator spec.

Yep, after the rfc update.

**Comment by michaelbarton** [comment]
> Ok, then I will update ray, soap and minia, so that their output is equal
> to velvet and state this in the rfc if this is not clear.

To clarify here, we'll put the output files in /bbx/output?

**Comment by pbelmann** [comment]
> To clarify here, we'll put the output files in /bbx/output?

Yes. Would this work for you?

**Comment by michaelbarton** [comment]
Yes, that's good for me.

**Comment by pbelmann** [comment]
Michael let's wait with this till thursday otherwise it will get tricky for the students.

**Comment by pbelmann** [comment]
bbx removed in master
